version: "3.8"

services:
  phishit-api:
    build:
      context: ./backend
    depends_on:
      - mongo
    ports:
      - 5000:5000

  phishit-ui:
    build:
      context: ./frontend
    depends_on:
      - phishit-api
    ports:
      - 3000:3000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  mongo-db:
  redis-data:
